services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bella-vista-postgres
    environment:
      POSTGRES_DB: bella_vista
      POSTGRES_USER: restaurante
      POSTGRES_PASSWORD: bella123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - restaurante-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurante -d bella_vista"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Etiquetas para identificación en monitoreo
    labels:
      - "monitoring.enable=true"
      - "monitoring.job=postgres"

  # Frontend Usuario
  frontend-usuario:
    build:
      context: ./frontend-usuario
      dockerfile: Dockerfile
    container_name: bella-vista-frontend-usuario
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: bella_vista
      DB_USER: restaurante
      DB_PASSWORD: bella123
      # Habilitar métricas para monitoreo
      ENABLE_METRICS: "true"
      METRICS_PORT: "3000"
    networks:
      - restaurante-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    # Etiquetas para identificación en monitoreo
    labels:
      - "monitoring.enable=true"
      - "monitoring.job=restaurante-frontend"

volumes:
  postgres_data:
    driver: local

networks:
  restaurante-network:
    driver: bridge
    name: bella-vista-network
