global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['bella-vista-postgres-exporter:9187']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['bella-vista-node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['bella-vista-cadvisor:8080']
    scrape_interval: 30s

  # Frontend Application Metrics
  - job_name: 'restaurante-frontend'
    static_configs:
      - targets: ['bella-vista-frontend-usuario:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Restaurant Application Metrics
  - job_name: 'restaurante-app'
    static_configs:
      - targets: ['bella-vista-frontend-usuario:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
